### ISSUE TITLE
Transition of User Stories & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#1]
User stories and personal info(Cenk Batman) should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![image](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by mcenkbatman** [comment]
Accepted

**Comment by mcenkbatman** [comment]
completed in less than half an hour.
