### ISSUE TITLE
Transition of Semantic Tagging and Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#10]
Semantic tagging and personal info should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"

Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by oeken** [comment]
Done: 
Personal info page : M. Onur Eken
Semantic tagging and searching page and it's subpages
