### ISSUE TITLE
Transition of Crowd Sourcing & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#11]
Crowd sourcing and personal info should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by serhatilbey** [comment]
Accepted.
Personal info page of mine is updated already.

**Comment by serhatilbey** [comment]
Issue is completed. 
Crowdsourcing page is imported.
It took 30 mins.
