### ISSUE TITLE
Transition of Mobile Mockups & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#12]
Semantic tagging and personal info should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"

Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by TahaK** [comment]
I accept the task.
Estimated time until finish : 1 hour.

**Comment by TahaK** [comment]
I have imported the personal info pages. However the semantic tagging pages were already imported by Mustafa Onur Eken.

**Comment by TahaK** [comment]
Done. Acual time 30 min.
