### ISSUE TITLE
Transition of Domain Analysis & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#14]
Domain Analysis and personal info should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by erensogut** [comment]
I will try to import test cases.I think it take half an hour.

**Comment by erensogut** [comment]
It is completed.
It took nearly half an hour.
