### ISSUE TITLE
Transition of Use Cases & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#3]
Use Cases and personal info(Murat Sinan Açlan) should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by mrtsnnacln** [comment]
accepted

**Comment by mrtsnnacln** [comment]
done
