### ISSUE TITLE
Transition of Web Mockups & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#4]
Web Mockups and personal info(Öykü Yılmaz) should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by oykuyilmaz** [comment]
Started.

**Comment by oykuyilmaz** [comment]
1)I transferred my personal info, web mockups and mobile mockups pages by copying their contents and fixing some image issues. 
2)I copied their links to home page and sidebar.

Time: 1 hour.
