### ISSUE TITLE
Transition of Sequence Diagrams & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#8]
Sequence diagrams and personal info should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by ugur2889** [comment]
Accepted

**Comment by ugur2889** [comment]
Started
Estimated Time: 0.5 hour

**Comment by ugur2889** [comment]
Done

**Comment by ugur2889** [comment]
Actual Time :2 hours
