### ISSUE TITLE
Transition of Class Diagrams & Personal Info Pages

### ISSUE THREAD

**Issue by silaguler** [bounswe2015group2/bounswe2015group2#9]
Class diagrams and personal info should be imported to GitHub Wiki. 
Wiki Edit mode could be chosen as "Markdown"
Deadline: sunday 12:01pm

![](https://cloud.githubusercontent.com/assets/12099819/7328524/ef2a7ba6-eade-11e4-824d-d8541f6d707a.png)

**Comment by bmertcotuk** [comment]
Accepted

**Comment by bmertcotuk** [comment]
Started
Estimated Time: 0.5 hour

**Comment by bmertcotuk** [comment]
Done
Actual Tİme: 0.5 hour
